### ISSUE TITLE
Banner images

### ISSUE THREAD

**Issue by 1000camels** [DenverArtMuseum/her-brush#10]
https://artsmia.github.io/tour-toolkit/tour-preparation/

**Comment by 1000camels** [comment]
I created a class for figures called full-width (ie. {{< q-figure id="2018-183" class="full-width">}} )

This can be adjusted but it pushes the image to full-screen and gives a 50px padding on either side

**Comment by vhellstein** [comment]
from Einor: banner images should be above titles, and pan up slightly as you scroll down

@1000camels  I'm not sure if that "pan up slightly as you scroll down" is possible or, if it is, if it's super time consuming to make happen. Let me know what you think.

**Comment by 1000camels** [comment]
I am working on this effect, but have not achieved it yet

**Comment by mpopke** [comment]
I've cropped the banner images, and added figures for them. The exhibition section pages are currently putting the title and calligraphy above the banners. I don't know if we want to change that or move those banners into the markdown as figures at the top of those pages. I haven't had a chance to dig around for those textures (for the calligraphy) yet so we might be able to set that aside for now in favor of more pressing matters until I get a chance to play around with those textures.
