### ISSUE TITLE
Artists’ bios

### ISSUE THREAD

**Issue by 1000camels** [DenverArtMuseum/her-brush#11]
First mention of name in essay will link to the artist’s bio. No pop-up boxes.

**Comment by 1000camels** [comment]
We have to decide how we want to manage the artist bios. They could be listed in the publication.yml as a contributor. It would be good to know how big the artist bios will be

**Comment by vhellstein** [comment]
[Artists_in_the_Exhibition_FINAL.md](https://github.com/DenverArtMuseum/her-brush/files/10523424/Artists_in_the_Exhibition_FINAL.md)
@1000camels: I tried to include this change/addition (the Artist bio text) in the new branch I made, but I don't know why I couldn't see it as a change I had been working on. So sending it to you here, so you have it.
