### ISSUE TITLE
Section Title Calligraphy by Tomoko Kawao

### ISSUE THREAD

**Issue by 1000camels** [DenverArtMuseum/her-brush#12]

**Comment by 1000camels** [comment]
We need to discuss whether these need to be images with the title text or separate images

**Comment by vhellstein** [comment]
Could we put them in the Banner space? Or! What if we use those calligraphy images on the Exhibition Catalog Landing page? Perhaps that's too much calligraphy on one page though? Open to options here. I just know Einor will want them somewhere.

**Comment by 1000camels** [comment]
Yes, I am working on getting these in. In the examples I have (in the Keynote), they are all placed in different ways. I will first attach them generally and then allow for individual styling. Just keep in mind, the more specific placement, the more work required to make sure the render well across all devices (and pdf, mobi and epub if we produce those)
