### ISSUE TITLE
Update ToC

### ISSUE THREAD

**Issue by 1000camels** [DenverArtMuseum/her-brush#14]
Update the order of the documents, changing the weight to place them in order. I've reserved 1xx for Exhibition and 2xx for Symposium, so it is easier to add and move within a directory.

Adding toc: false to the page metadata will remove that page from the TOC

**Comment by 1000camels** [comment]
updated toC is different from the keynote. Not sure which is correct

**Comment by vhellstein** [comment]
Please use the updated ToC I sent you--that was the last that Einor approved. Sorry for the confusion! Also, Karuna's essay which is currently without title is: Galleries as Sites of Connection: Visitor Experience in _Her Brush_.
