### ISSUE TITLE
Markup Japanese text with lang codes

### ISSUE THREAD

**Issue by mpopke** [DenverArtMuseum/her-brush#16]
In order for Japanese language specific styles to apply to the text, Japanese characters need to be marked up with lang attributes. In most cases this requires wrapping Japanese text with `<span lang="ja">` tags. I can do this with a regex search and replace for the most part.

**Comment by mpopke** [comment]
Went through and encoded Japanese strings with appropriate lang attributes. Will need to remember to continue encoding new content appropriately. [368895a](https://github.com/DenverArtMuseum/her-brush/commit/368895a3677a1bda28db888c605d476b56aa8d7c)

**Comment by 1000camels** [comment]
I can see the font being used
