### ISSUE TITLE
Title page feedback

### ISSUE THREAD

**Issue by vhellstein** [DenverArtMuseum/her-brush#18]
--The image seems rather dark. Can we lighten it a bit?
--I feel like there's too much space between "Her" and "Brush"--can we make those closer together? I'd be okay with the subtitle being a bit wider than the main title
--Do we need arrows at both the top and bottom of the page?

**Comment by 1000camels** [comment]
I will work on those first two items
I have removed the arrow on the top of the cover page as Einor requested. In general, the buttons at the bottom are good for when the page scrolls, as the navbar does disappear part way down the page.

**Comment by 1000camels** [comment]
These changes have been made and now reflected on github.io
