### ISSUE TITLE
Table of Contents feedback

### ISSUE THREAD

**Issue by vhellstein** [DenverArtMuseum/her-brush#20]
--Maybe only list symposium contributors names instead of including "essay"--the ToC already feels very heavy, so I'm hesitant to include full essay titles on the main ToC. What do you think?
--in the ToC dropdown on the left--can we change the highlighted current page to the blue of the title instead of red?

**Comment by 1000camels** [comment]
I am working on this. My plan is to show Essay in the TOC (sidebar) and possibly the full title in the Contents. However this is not built into Quire by default, so I am changing the templates and adding additional page metadata, so we can control the various titles

**Comment by vhellstein** [comment]
@1000camels : If I can change the text on the Table of Contents, page I'm happy to do that if you point to where I can make changes. If it's easier for you/you'd rather make those changes:
1. make apostrophe in Collector's curly--not straight (Also on the Collector's Note page)
2. for symposium section: delete "Her Brush:" and ": A Symposium"
3. Change "Study Collection" to "On the Fong-Johnstone Study Collection and the Power of Access"

**Comment by 1000camels** [comment]
These are all changes to the documents, as the TOC is generated from the page metadata.
I can do it
