### ISSUE TITLE
Sitewide feedback

### ISSUE THREAD

**Issue by vhellstein** [DenverArtMuseum/her-brush#22]
--Table of Contents (main + symposium): Instead of a / I think | would be better. (If this is a content thing I can change, happy to do that)
--footnotes need to be more of a superscript. Pop-ups are good though. Should also be listed at end of essays under "Notes"
--Can we get rid of the big quotation mark at the beginning of indented quotes?
--A lot of the vertically oriented images seem too big--there's a lot of scrolling to get past them. Perhaps better to make all the exhibition catalog texts with 2 columns. I think this would make the relationship between text and image clearer, too.
--Depending on the screen, the space between the text and image columns can be very tight.

**Comment by 1000camels** [comment]
The / is in a template (layouts/partials/contents-list/list-items-type/default.html), so I have changed it.
i've updated footnotes.
That might be a character encoding. Can you point me to a specific example?
I am working to convert most of the pages to two columns and in general to get more space. I am trying to establish a few templates that can be used to make these layouts easier to apply
I'll work on the overall spacing

**Comment by vhellstein** [comment]
You can see an example of the big quotation mark in an indented quote in Fister's longer essay--before footnote 27.

**Comment by 1000camels** [comment]
Oh yes. This is code across the site to create this drop cap effect across
the site. I have already removed it in footnotes. I can remove it here or
even across the whole site
