### ISSUE TITLE
Exhibition Catalog ToC

### ISSUE THREAD

**Issue by vhellstein** [DenverArtMuseum/her-brush#23]
I think it will be good to embed the eventual video below the banner on this page, and then have the install images paired with their sections.

**Comment by 1000camels** [comment]
Do we know where the video will be posted?

**Comment by vhellstein** [comment]
@mpopke will this be on YouTube or Vimeo? What are we using these days? Would it live someplace different? It would be ready to post until the end of March probably.

**Comment by 1000camels** [comment]
I have brought the kanji onto the Exhibition TOC: https://denverartmuseum.github.io/her-brush/exhibition/
We can also add the embedded video when it is ready

**Comment by vhellstein** [comment]
@1000camels Matt and I really like the kanji here! Einor wondered if there might also be detail install shots, but I fear that may be visual overload. The black and white of the background, text, and kanji is a pretty stark contrast...can you tone down the brightness a bit on the white? Or would making the background the same color as the title text/accent color be weird?

**Comment by 1000camels** [comment]
I do not have a kanji for introduction but I do have one for Her Brush
