### ISSUE TITLE
Contributors

### ISSUE THREAD

**Issue by vhellstein** [DenverArtMuseum/her-brush#25]
--Instead of linking to individual content, can we have short bios instead? (I can add that content if I haven't already)
--Let's only list those who wrote text here. Delete Valerie, Renee, Matt, and Douglas. I'll include them on the About page.

**Comment by 1000camels** [comment]
The way the contributors work is that we can add anyone and everyone to the list and then place them in different groupings, so they can be displayed automatically. Of course, we do not have to include you all in that way, but it might be easier for rendering. But really it is up to you. For now, I will switch you all to a different group, staff, so you no longer appear

**Comment by 1000camels** [comment]
I have added staff as a list on the about so you can see what I mean

**Comment by vhellstein** [comment]
This is great, @1000camels. Where can I add short bios for the contributors? I'd like to see that info before the links to their essay contributions...also, can we make that link text smaller?

**Comment by 1000camels** [comment]
Bios go into the data/publication.yml https://github.com/DenverArtMuseum/her-brush/blob/main/data/publication.yml
