### ISSUE TITLE
Resources

### ISSUE THREAD

**Issue by vhellstein** [DenverArtMuseum/her-brush#26]
--let's rename Additional Resources
--Bibliography list should populate this page
--Can we delete the Author Year ID from above each entry?

**Comment by 1000camels** [comment]
Which year do you want to delete? The entries are in references.yml and are titled Adiss 1990, as a way to distinguish from Adiss 1995. And the other year is just in the full listing

**Comment by vhellstein** [comment]
Can we just not have the ID display above each entry? Just the alphabetical list is fine. We don't use the Author Date ID in any of the essay texts, so it seems strange to me to display those.
