### ISSUE TITLE
Mouse over popup footnotes

### ISSUE THREAD

**Issue by 1000camels** [DenverArtMuseum/her-brush#3]
https://50x50.sjmusart.org/asawa/#drawing-dance-and-architecture

**Comment by 1000camels** [comment]
Using littlefoot.js

**Comment by 1000camels** [comment]
We can adjust the styles of the footnotes to whatever you think looks good

**Comment by 1000camels** [comment]
Also show the footer notes

**Comment by vhellstein** [comment]
I added this to my sitewide feedback but I'll add here too:
--let's make the footnote more of a superscript. But pop-ups are good.

**Comment by 1000camels** [comment]
By superscript, you just mean you want the number to appear above the line, not below?

**Comment by vhellstein** [comment]
@1000camels In the list of footnotes at the end of the essays, can we bring back the numbers before them? Can I just add those in the markdown file?
