### ISSUE TITLE
Text styling

### ISSUE THREAD

**Issue by vhellstein** [DenverArtMuseum/her-brush#35]
--reduce font size of subtitle headings in essays
--slightly bigger breaks between paragraphs
--color of title and name of Director's foreword and Collector's note should be the same color as title font on cover page
--all page titles on the right and below banner images (see Einor's keynote file)
--in some cases, clicking on an underlined hyperlink added yellow highlight. Please remove highlight.
--japanese text next to English not below it-- @1000camels is this a change I can make in the markdown files?

**Comment by 1000camels** [comment]
Where are you seeing the japanese next to the English? I did attempt to place the english and japanese poems next to each other using {{< q-class "flexbox-column" >}}, which is a way of inserting markup around text

I can push the titles below the banner images

**Comment by vhellstein** [comment]
It's perfect in Einor's On the Fong-Johnstone Study Collection essay, but in the Introduction section of the Exhibition catalog, the Japanese is below the English. I can look at the markup in Einor's essay and then replicate it when I see the issue in other places (or maybe just this one place).
