### ISSUE TITLE
Cover page feedback

### ISSUE THREAD

**Issue by vhellstein** [DenverArtMuseum/her-brush#36]
-Can we crop the image in the cover page differently? Please refer to the keynote. I want it more abstracted and accentuate the materials (silk, gold, mineral green pigment, etc.)
-text in title and DAM logo should be the same opacity & color

**Comment by 1000camels** [comment]
Yes, we can. There are opens for positioning the image, but it is easier if we produce a banner image to fit. Banner images are best cropped to 1600 x 500 pixels (16:9 aspect ratio)
