### ISSUE TITLE
Caption style for banner images

### ISSUE THREAD

**Issue by vhellstein** [DenverArtMuseum/her-brush#37]
We'll need to make sure all banner images and other images on pages not called out in the text have captions. Darcy, Matt and I were just thinking of a small paragraph at the end of the page where necessary, in slightly smaller font.

**Comment by 1000camels** [comment]
I am working on a solution.
Quire just lets you select images by file name, but if I can specify them by figure id, I will be able to get the credit and display it

**Comment by 1000camels** [comment]
This is done, but credit lines may need to be added and the page itself must reference the id not the image
