### ISSUE TITLE
color block behind essay text

### ISSUE THREAD

**Issue by vhellstein** [DenverArtMuseum/her-brush#38]
Einor didn't like the color behind the text on the Collector's note or the Fister essays. She wasn't entirely against them in theory, but she thought they made the page seem too narrow. Perhaps a point to clarify in the upcoming meeting. But probably will need to delete

**Comment by 1000camels** [comment]
I've fixed the background image, so let's discuss this in context of the background images.

**Comment by vhellstein** [comment]
Let's just not worry about background colors behind the text at this point
