### ISSUE TITLE
Travel Journal image

### ISSUE THREAD

**Issue by vhellstein** [DenverArtMuseum/her-brush#42]
For object 2021.206: featured in the Taking the Tonsure section. 

I think this got lost in the discussions, but originally, Einor wanted to be able to click on the image and then scroll through all of the pages. I know that this would be easier for the Exhibition Checklist if we had each object have it's own page. Can we do it just for this instance of the image in this section though? Or if that is too onerous, can we stitch together a selection of pages into one image that spans the screen's width? Or use 3 or 4 separate images on one line? What's the most efficient solution at this point?

**Comment by vhellstein** [comment]
@mpopke this might be another image for you to work on while your cropping.

**Comment by mpopke** [comment]
Considering the images we have I think it makes the most sense to have a page for this object, and just put all of the figures for this object on it. Stitching the images together wouldn't look great. I have added all of the images to the repo, and added figures for them in figures.yml.

I think the easiest way to do that is create a new page that isn't the ToC anywhere, and link to it in the caption of the figure we are currently using for this object.

**Comment by 1000camels** [comment]
Another way is to add the images into the page and hide them. When you click on the book, and page through the images, you see them. I am committing this so you can see it. You will likely want to fix the captions for each image, which can be done in figures.yml or in the taking.md and the q-figure tag

**Comment by 1000camels** [comment]
Another option is to use the q-figure-group https://quire.getty.edu/docs-v0/figure-images/#create-and-style-figure-groups-with-q-figure-group-shortcode

**Comment by geealbers** [comment]
FYI for the future, we're working on a new feature in Quire v1 that allows for figures to have sequences of many individual images. Out of the box it will have support to display those sequences in a click and drag interface to facilitate 360-degree object rotations (displaying one rotational view from the sequence at a time). But the underlying idea is that users could modify it to display the sequences in other ways as well: pages in a book, slide carousels, stitched together, etc.
