### ISSUE TITLE
Set up domain name for final publication

### ISSUE THREAD

**Issue by mpopke** [DenverArtMuseum/her-brush#43]
@mpopke I would like to start discussing how you plan to deploy to your website.
I believe you mentioned it would be on AWS.
I can create a deployment script that models the bin/deploy.sh, but pushes the site code to a new branch and then we can discuss whether there is a process to pull the branch to the server.
As soon as you have a domain, I can set up the deploy to use that url, so that the images render correctly.

**Comment by mpopke** [comment]
I have finally gotten this working. We had a DNS misconfiguration issue on our network that took a moment to diagnose before I could see what I was doing on this.

The address on GitHub pages is her-brush.denartmus.org, and there is a redirect from publications.denartmus.org/her-brush that points to it. The SSL certificate for github has been provisioned and is currently propagating through their infrastructure. They say it could take up to an hour for that to complete, so some people might see security errors when navigating to the site until that propagation is complete. Hopefully, that will take care of itself soon. I'll double check later this morning to make sure it's working properly.

**Comment by 1000camels** [comment]
I saw the domain and a redirect from the old github.io. I updated the url in github.yml, but after republishing, it is not appearing at the new domain. Not sure what I did wrong

**Comment by mpopke** [comment]
That's weird. It was working for me on Thursday, and it's working for me this morning (I put the domain back in the settings). In order for github to use the domain name, there needs to be a CNAME file in the target branch. That file is just a text file with the domain name on a single line (no http:// or path, just the domain name). Github doesn't like it when that file is missing.

Perhaps when you rebuilt the site, it removed that file from the gh-pages branch? Is there a config file we're missing somewhere that would add that file to Quire's build settings?

**Comment by mpopke** [comment]
I also found when deploying from my end, that I had to edit the deploy.sh action to --force the gh-pages branch to push. Github modifies the gh-pages branch on it's end (adds the CNAME file) so the push is no longer a fast-forward when building a fresh gh-pages branch.

**Comment by 1000camels** [comment]
I understand now. I have added the CNAME file to the static directory, so it gets copied into site each time it is built. It seems to work fine.

I still run into clashes with the deployment. The only solution I found is to delete the gh-pages, which is fine, but does require resetting that as the github pages branch to use for deployment.
