### ISSUE TITLE
caption for Travel journal

### ISSUE THREAD

**Issue by vhellstein** [DenverArtMuseum/her-brush#50]
This is in Taking the Tonsure section: 2021.206.

I'd love to add to the end of the caption *just on this page* where there is the feature that you can see all the pages: Click on the image to see more pages from the _Travel Journal_.

But I wasn't sure where exactly to add that additional caption in the Markdown file...

**Comment by 1000camels** [comment]
![Screen Shot 2023-03-24 at 9 21 30 AM](https://user-images.githubusercontent.com/689727/227377803-fb03e60e-7300-463c-b09b-a918a0948197.png)
Does this work?

**Comment by vhellstein** [comment]
Wonderful!
