### ISSUE TITLE
In Floating Worlds section

### ISSUE THREAD

**Issue by vhellstein** [DenverArtMuseum/her-brush#51]
Delete slash after Kikaku’s name after Star Festival quote宝井其角\  

Darcy: It looked like all of the Japanese lines in this quote ended with a slash, so I didn't want to delete this one...but we shouldn't see it on the screen.

**Comment by 1000camels** [comment]
the backslash is markdown way of adding <br />. But for some reason it is not translated at the end where a html element starts, so it just needs to be removed there. 

I have converted them back to <br /> and removed the last one
