### ISSUE TITLE
In Literati Circles section

### ISSUE THREAD

**Issue by vhellstein** [DenverArtMuseum/her-brush#52]
Include image of box (RA.2021.198.1-5) after “This group of plates is also rare for its impeccable documentation. Their original box bears an inscription of authenticity by Priest Kōen of the Jinkō-in temple, where Rengetsu once lived.”

Darcy: don’t know if it’s possible, but could also be smaller and to the right of the text below the plates

**Comment by 1000camels** [comment]
![Screen Shot 2023-03-24 at 9 30 40 AM](https://user-images.githubusercontent.com/689727/227379130-917388ff-2d62-4e26-8aef-5c695d7a3bda.png)
Like this?

**Comment by vhellstein** [comment]
No, there should be a new image there RA.2021.198.1-5, which I think should be in the objects.yml

**Comment by 1000camels** [comment]
![Screen Shot 2023-03-24 at 9 39 34 AM](https://user-images.githubusercontent.com/689727/227380348-82a0c336-64fe-434a-a2b0-b3f41990ce7c.png)
this?

**Comment by vhellstein** [comment]
That's it!

**Comment by 1000camels** [comment]
What does RA mean?
There is not an RA.2021.198.1-5 on objects.yml or figures.yml

**Comment by 1000camels** [comment]
Oh good
