### ISSUE TITLE
In Unstoppable section

### ISSUE THREAD

**Issue by vhellstein** [DenverArtMuseum/her-brush#53]
Darcy we need to add this image after "These artists dared to leave their enduring mark through art." And then give some buffer space between it and the next block of text/image

id: early-views
    src: figures/HerBrushEarlyViews17.jpg

**Comment by 1000camels** [comment]
![Screen Shot 2023-03-24 at 9 34 15 AM](https://user-images.githubusercontent.com/689727/227379599-16eaf297-c9b3-453a-833c-15a74781ba6e.png)
How does this look?

**Comment by vhellstein** [comment]
Yes! Does the caption show up too? (without "fig. 1" as in Karuna's essay. Should just be: A visitor in front of the interactive video projection in the last gallery of _Her Brush_, 2022. Photograph by Eric Stephenson.

**Comment by 1000camels** [comment]
![Screen Shot 2023-03-24 at 9 42 17 AM](https://user-images.githubusercontent.com/689727/227380742-ebae9e9d-00db-4baf-ab37-abe0fe2ed640.png)
Yes
