### ISSUE TITLE
Introduction:

### ISSUE THREAD

**Issue by vhellstein** [DenverArtMuseum/her-brush#56]
Extra space before paragraph "This poetry slip..."

Before “2018.259.1-2.” Add subheading: “Rengetsu’s Legacy” and right below, include  2018.245& 2021.156 side by side (then, below them, 2018.259.1-2, accompanied by 2 details of seal.+ text (2018_259_1_4 and 2019_259_1_5 )

Caption for both: Kuroda Kōryō 黒田光良, 1823–1895, _Teabowl in the Style of Rengetsu_ (_Rengetsu-yaki_) (detail), late 1800s. Glazed ceramic. Gift of Drs. John Fong and Colin Johnstone, 2018.259.1.

2018_259_1_4 Alt text: a photo of the rough outside of the teabowl with a small stamp in the center. 

2018_259_1_5 Alt text: a photo of a close-up of the small stamp on the rough outside of the teabowl.

**Comment by 1000camels** [comment]
I cannot locate 2018_259_1_4 and 2019_259_1_5  and these instructions are confusing. I am sorry, I do not understand whether which captions go with which.
Also, alt text is different from Caption and generally is set in the figures.yml

**Comment by 1000camels** [comment]
I think I got it right

**Comment by vhellstein** [comment]
You did! Thanks!
