### ISSUE TITLE
Taking the Tonsure

### ISSUE THREAD

**Issue by vhellstein** [DenverArtMuseum/her-brush#59]
•	Move the intro quote (Not coiffuring my hair…) after paragraph that starts “Leaving their old names behind…” + Add some space between it and the paragraph + add some space after it and the paragraph that starts “The nun-artist Otagaki…” (styled like other block quotes)
•	Photograph of Ōishi Junkyō to appear right next to her bio focus, small, and against a different color background to clarify distinction. (like bio focus in introduction)
•	Add 2018.156 to accompany Junkyō’s bio focus.
•	Use woodblock portrait of Ryōnen Gensō as an illustration for her bio focus and treat differently. Her actual calligraphy should take up the space instead. (like bio focus in introduction)

**Comment by 1000camels** [comment]
I do not understand "against a different color background to clarify distinction. (like bio focus in introduction)"

**Comment by 1000camels** [comment]
Or maybe I understand what you mean. Have a look
