### ISSUE TITLE
Floating Worlds

### ISSUE THREAD

**Issue by vhellstein** [DenverArtMuseum/her-brush#60]
•	Move 2018.181.4-44 + its text (“These poetry slips (tanzaku…appear in the next section”) after “Eternal art in a floating world” with some buffer space between; enlarge image. 2018.226 should be smaller and to the right (like 2018.181.4-44 was) Add space between end of that text and 2018.183

•	Minimize size of woodblock illustration of the teahouse and place alongside the bio focus. Teahouse illustration should be smaller, to the right, aligned with “Kaji, Yuri, and Machi…” 

•	Add 2 objects after the 3 women of gion bio focus: (1) 2018.181.1 & (2) 2018.186 (use image that includes mounting). They can be side by side (but large, please). Matt added the new images to the repo.

**Comment by 1000camels** [comment]
done
