### ISSUE TITLE
Literati Circles

### ISSUE THREAD

**Issue by vhellstein** [DenverArtMuseum/her-brush#61]
•	At the end of the page, include 2018.206 and place side by side with 2018.196 (move below the paragraph)
•	For Okuhara Seiko Bio Focus, include 2018.247A-B below portrait
•	Add the two fans side by side: 2018.195 & 2018.201 below Shohin bio focus

**Comment by 1000camels** [comment]
2018.247A-B, 2018.195 and 2018.201 do not have captions. They should be added in figures.yml

**Comment by vhellstein** [comment]
Done!
