### ISSUE TITLE
Exhibition Checklist

### ISSUE THREAD

**Issue by vhellstein** [DenverArtMuseum/her-brush#62]
•	not in order. order should match order here: https://www.denverartmuseum.org/en/her-brush-companion-guide-checklist--Darcy, if this is something I can do, I'm happy to.
•	2018.218 is missing from checklist—should be in Inner Chambers

**Comment by 1000camels** [comment]
Do you just mean in terms of order?
This is controlled in https://github.com/DenverArtMuseum/her-brush/blob/main/data/objects.yml

**Comment by vhellstein** [comment]
Hmmm...so the object yamls are in the order that matches the link above and includes the 2018.218 that seems to be missing...so it seems strange that the checklist isn't following that order, right?

**Comment by 1000camels** [comment]
I am sorry, they are being alphabetically sorted. Shall I remove that and just let them be displayed in the order they appear?

**Comment by 1000camels** [comment]
fixed
