### ISSUE TITLE
Interesting Table of Contents layout

### ISSUE THREAD

**Issue by 1000camels** [DenverArtMuseum/her-brush#9]
https://artsmia.github.io/alcohols-empire/contents/

**Comment by 1000camels** [comment]
These are archived with the grid class on contents pages (ie. the pagename-index.md page for each directory)

type: contents
class: grid

**Comment by vhellstein** [comment]
@1000camels: we need to rethink the styling a bit here to make it clearer. I can work on this in the markdown files if that's where the info is being pulled from. (e.g. authors names not italics, maybe some bolding...)

**Comment by 1000camels** [comment]
I have bolded them
